services:
  - type: web
    name: hexagons-backend
    env: node
    plan: standard
    buildCommand: yarn && yarn build
    startCommand: yarn start
    healthCheckPath: /admin
    region: frankfurt
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
envVarGroups:
- name: backend-v4
  envVars:
  - key: NODE_ENV
    value: production
  - key: APP_KEYS
    value: CHANGE-ME
  - key: API_TOKEN_SALT
    generateValue: true
  - key: ADMIN_JWT_SECRET
    generateValue: true
  - key: JWT_SECRET
    generateValue: true
  - key: NODE_VERSION
    value: 16.14.0
  - key: HUMAN_EMAIL
    value: CHANGE-ME
  - key: ROBOT_EMAIL
    value: CHANGE-ME
  - key: ROBOT_PASSWORD
    value: CHANGE-ME
  - key: CUSTOM_URL
    value: https://foo-backend.hexagons.app
  - key: SMTP_HOST
    value: smtp.office365.com
  - key: SMTP_PORT
    value: 587
  - key: DATABASE_HOST
    value: CHANGE-ME
  - key: DATABASE_PORT
    value: CHANGE-ME
  - key: DATABASE_NAME
    value: CHANGE-ME
  - key: DATABASE_USERNAME
    value: CHANGE-ME
  - key: DATABASE_PASSWORD
    value: CHANGE-ME
  - key: DATABASE_SSL
    value: false
  - key: DATABASE_SCHEMA
    value: public
databases:
  - name: strapi-v4
    plan: professional
    region: frankfurt
