services:
  - type: web
    name: hexagons-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /admin
    region: frankfurt
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
envVarGroups:
- name: backend
  envVars:
  - key: NODE_ENV
    value: production
  - key: ADMIN_JWT_SECRET
    generateValue: true
  - key: DATABASE_URL
    value: CHANGE-ME
  - key: JWT_SECRET
    generateValue: true
  - key: NODE_VERSION
    value: 16.14.0
  - key: HUMAN_EMAIL
    value: CHANGE-ME
  - key: ROBOT_EMAIL
    value: CHANGE-ME
  - key: ROBOT_PASSWORD
    value: CHANGE-ME
  - key: SMTP_HOST
    value: smtp.office365.com
  - key: SMTP_PORT
    value: 587
databases:
  - name: strapi
    plan: standard
    region: frankfurt
